name: Build and Release Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Binary
      run: |
        go build -o url-checker-$(git describe --tags --always --dirty)
        echo "Binary name: url-checker-$(git describe --tags --always --dirty)"

    - name: Upload Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./go-hello-$(git describe --tags --always --dirty)
        asset_name: go-hello-$(git describe --tags --always --dirty)
        asset_content_type: application/octet-stream


    - name: Create Git Tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        git tag -a ${{ github.ref }} -m "Release ${{ github.ref }}"
        git push origin ${{ github.ref }}


        